language: erlang
otp_release:
   - R15B02
   - R15B01
   - R15B

before_script:
  - sudo apt-get install libpcap-dev

# try to narrow down the set of modules that cause the test failure:
script: "make compile && ./rebar eunit skip_deps=true apps=linc,linc_us4 suites=linc_us4_queue_tests,linc_us4_tests"
